import smtplib
from email.mime.text import MIMEText

# Configuration
port = 587
smtp_server = "smtp.gmail.com"
login = "dhavalparmar7727@gmail.com"  # Your login generated by Mailtrap
password = "aoks remz hbhu cmfn"  # Your password generated by Mailtrap

sender_email = "dhavalparmar7727@gmail.com"
receiver_email = "atulk.doc@gmail.com"

# Plain text content
text = """\
Hi,
Check out the new post on the Mailtrap blog:

"""

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "Plain text email"
message["From"] = sender_email
message["To"] = receiver_email

# Send the email
with smtplib.SMTP(smtp_server, port) as server:
    server.starttls()  # Secure the connection
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')